/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ProjectSummarizerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/data-fetcher.ts
var import_obsidian = require("obsidian");
var DataFetcher = class {
  constructor(app) {
    this.projectFiles = /* @__PURE__ */ new Set();
    this.app = app;
  }
  /**
   * Initializes the index by scanning all markdown files for the #project tag.
   */
  async initializeIndex() {
    const files = this.app.vault.getMarkdownFiles();
    for (const file of files) {
      this.checkAndAddFile(file);
    }
    console.log(`[DataFetcher] Initialized index with ${this.projectFiles.size} project files.`);
  }
  /**
   * Checks if a file has the #project tag and updates the internal index.
   */
  checkAndAddFile(file) {
    var _a, _b;
    const cache = this.app.metadataCache.getFileCache(file);
    const tags = ((_a = cache == null ? void 0 : cache.tags) == null ? void 0 : _a.map((t) => t.tag)) || [];
    const frontmatterTags = ((_b = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _b.tags) || [];
    const allTags = [...tags, ...Array.isArray(frontmatterTags) ? frontmatterTags : [frontmatterTags]];
    if (allTags.some((t) => t.includes("project"))) {
      this.projectFiles.add(file.path);
    } else {
      this.projectFiles.delete(file.path);
    }
  }
  /**
   * Removes a file from the index (e.g. when deleted).
   */
  removeFile(path) {
    this.projectFiles.delete(path);
  }
  /**
   * Compiles summaries for all indexed project files.
   */
  async getAllProjectSummaries() {
    var _a;
    const summaries = [];
    for (const path of this.projectFiles) {
      const file = this.app.vault.getAbstractFileByPath(path);
      if (file instanceof import_obsidian.TFile) {
        const cache = this.app.metadataCache.getFileCache(file);
        summaries.push({
          path: file.path,
          title: file.basename,
          tags: ((_a = cache == null ? void 0 : cache.tags) == null ? void 0 : _a.map((t) => t.tag)) || [],
          frontmatter: (cache == null ? void 0 : cache.frontmatter) || {},
          lastModified: file.stat.mtime
        });
      }
    }
    return summaries;
  }
};

// src/main.ts
var DEFAULT_SETTINGS = {
  projectFolderPath: "",
  indexFilePath: "project-index.md",
  logFilePath: "project-log.md"
};
var ProjectSummarizerPlugin = class extends import_obsidian2.Plugin {
  async onload() {
    console.log("Loading Project Summarizer Skill...");
    await this.loadSettings();
    this.dataFetcher = new DataFetcher(this.app);
    this.app.workspace.onLayoutReady(async () => {
      await this.dataFetcher.initializeIndex();
    });
    this.registerEvent(
      this.app.metadataCache.on("changed", (file) => {
        if (file instanceof import_obsidian2.TFile) {
          if (this.isWithinScope(file)) {
            this.dataFetcher.checkAndAddFile(file);
          }
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("delete", (file) => {
        this.dataFetcher.removeFile(file.path);
      })
    );
    this.addCommand({
      id: "generate-project-summary",
      name: "Generate Project Summary",
      callback: async () => {
        const summaries = await this.dataFetcher.getAllProjectSummaries();
        new import_obsidian2.Notice(`Found ${summaries.length} project(s). Check console for details.`);
        console.log("Project Summaries:", summaries);
        await this.updateIndexFile(summaries);
        await this.appendToLog("Generated project summary for " + summaries.length + " projects.");
      }
    });
    this.addSettingTab(new ProjectSummarizerSettingTab(this.app, this));
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  isWithinScope(file) {
    if (!this.settings.projectFolderPath) return true;
    return file.path.startsWith(this.settings.projectFolderPath);
  }
  async updateIndexFile(summaries) {
    const indexPath = this.settings.indexFilePath;
    let content = "# Project Index\n\nGenerated at: " + (/* @__PURE__ */ new Date()).toLocaleString() + "\n\n";
    summaries.forEach((s) => {
      var _a;
      content += `- [[${s.path}|${s.title}]] (Status: ${((_a = s.frontmatter) == null ? void 0 : _a.status) || "N/A"})
`;
    });
    const existingFile = this.app.vault.getAbstractFileByPath(indexPath);
    if (existingFile instanceof import_obsidian2.TFile) {
      await this.app.vault.modify(existingFile, content);
    } else {
      await this.app.vault.create(indexPath, content);
    }
    new import_obsidian2.Notice(`Updated ${indexPath}`);
  }
  async appendToLog(message) {
    const logPath = this.settings.logFilePath;
    const entry = `
## [${(/* @__PURE__ */ new Date()).toISOString().split("T")[0]}] ${message}
`;
    const existingFile = this.app.vault.getAbstractFileByPath(logPath);
    if (existingFile instanceof import_obsidian2.TFile) {
      const currentContent = await this.app.vault.read(existingFile);
      await this.app.vault.modify(existingFile, currentContent + entry);
    } else {
      await this.app.vault.create(logPath, "# Project Log\n" + entry);
    }
  }
};
var ProjectSummarizerSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Project Summarizer Settings" });
    new import_obsidian2.Setting(containerEl).setName("Project Folder Path").setDesc("Limit scanning to this folder (leave empty for whole vault)").addText((text) => text.setPlaceholder("e.g. Projects/").setValue(this.plugin.settings.projectFolderPath).onChange(async (value) => {
      this.plugin.settings.projectFolderPath = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("Index File Path").setDesc("Path to the generated index file").addText((text) => text.setValue(this.plugin.settings.indexFilePath).onChange(async (value) => {
      this.plugin.settings.indexFilePath = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("Log File Path").setDesc("Path to the generated log file").addText((text) => text.setValue(this.plugin.settings.logFilePath).onChange(async (value) => {
      this.plugin.settings.logFilePath = value;
      await this.plugin.saveSettings();
    }));
  }
};
